##############################################################
#
# $ID$
#
# Makefile for host2storagemap 
#
# 
# Copyright 2005 Network Appliance, Inc. All rights     
# reserved. Specifications subject to change without notice.    
#                                                            
# This SDK sample code is provided AS IS, with no support or    
# warranties of any kind, including but not limited to       
# warranties of merchantability or fitness of any kind,      
# expressed or implied.  This code is subject to the license    
# agreement that accompanies the SDK.                        
#                                                            
##############################################################

	
all:host2storagemap 

host2storagemap: host2storagemap.c 
	gcc $(CFLAGS) -o host2storagemap host2storagemap.c

clean:
	rm -f host2storagemap 
	

