/*
 * Copyright (c) 2001-2005 Network Appliance, Inc.
 * All rights reserved.
 *
 * *** NOTE *** DO NOT EDIT THIS FILE - it is generated by dfm-zapidoc.
 * *** Generated: Mon Jul 25 14:14:04 2011
 */

#define EABORTINPROGRESS 21024
/* Error when dfm backup abort is already in progress */

#define EACCESSDENIED 22256
/* Access denied to system objects. */

#define EAGENTNOTUPTODATE 22321
/* Host agent version is too old to support the requested operation. */

#define EALARMDOESNOTEXIST 22233
/* Specified alarm does not exist */

#define EALARMTESTFAILED 22280
/* Alarm test operation failed. */

#define EALREADYACKWED 22258
/* Event is already acknowledged. */

#define EALREADYINDATASET 22241
/* Member already in dataset. */

#define EAPPPOLICYINUSE 23806
/* The Application Policy is in use by one or more datasets. */

#define EAPPPOLICYNOTFOUND 23821
/* Application policy not found. */

#define EBACKUPBUSY 23410
/* The specified backup is busy. */

#define EBACKUPDOESNOTEXIST 22281
/* Backup Version does not exist */

#define EBACKUPLOCATIONDOESNOTEXIST 22290
/* The specified backup location was not found. */

#define EBACKUP_ALREADY_MOUNTED 23825
/* Backup is already mounted. */

#define EBACKUP_NOT_MOUNTED 23826
/* Backup is not mounted. */

#define EBADCREDENTIALS 21008
/* Credentials are believed to be invalid */

#define EBADHOSTTYPE 22265
/* Unknown host type. */

#define ECANNOTDELETECLUSTERNODEHOST 23815
/* Controllers host that belong to a cluster cannot be deleted individually. */

#define ECANNOTDESTROYSTORAGE 23345
/* The storage system (volume, lun or qtree) cannot be destroyed. */

#define ECANTREADCONFIGFILE 21006
/* Fail to read configuration file */

#define ECANTREADSTATUSFILE 21009
/* Fail to read status file */

#define ECANTWRITECONFIGFILE 21007
/* Fail to write configuration file */

#define ECLIENTSTATSCOLLECTIONINPROGRESS 23522
/* Collection of per-client statistics is already in progress. */

#define ECOMMENTFIELDALREADYEXISTS 23301
/* Comment field already exists. */

#define ECOMMENTFIELDDOESNOTEXIST 23302
/* Comment field does not exist. */

#define EDATABASEERROR 22259
/* Database Error. */

#define EDATASETBUSY 23805
/* Dataset is busy with conformance or migration tasks. */

#define EDATASETDRSTATEUNCHANGED 23401
/* A request was made to make an idempotent update to the DR state of a dataset. */

#define EDATASETEXISTS 22212
/* Dataset already exists. */

#define EDATASETFAILINGOVER 23416
/* A request to modify the dataset failed because the dataset's DR State is currently "Failing Over". */

#define EDATASETFAILOVERNOTREADY 23402
/* A failover request failed because the dataset was not in the "Ready" state. */

#define EDATASETMIGRATING 23510
/* Dataset is migrating. */

#define EDATASETNODEISROOT 22246
/* Dataset node is root. */

#define EDATASETNOTDRCAPABLE 23408
/* The dataset is not DR capable. */

#define EDATASETNOTEFFECTIVEPRIMARY 23411
/* Operation on the dataset is only valid for the effective primary node. */

#define EDATASETNOTEMPTY 22239
/* Dataset is not empty. */

#define EDATASETNOTINFAILEDOVERSTATE 23409
/* The dataset is not in the "Failed Over" state. */

#define EDATASETNOTINSTABLEDRSTATE 23412
/* The dataset is not in a stable DR state. */

#define EDATASETWRONGDRSTATE 23400
/* A request was made to update the DR state of a dataset to an invalid state. */

#define EDEDUPEABORTNOTSUPPORTED 23503
/* Aborting a deduplication operation is not possible as deduplication on the storage system is not running. */

#define EDEDUPEALREADYRUNNING 23505
/* Running deduplication is not possible if deduplication on the volume is already running on the storage system. */

#define EDEDUPENOTRUNNING 23506
/* Aborting deduplication is not possible if deduplication is not running on the storage system. */

#define EDEDUPENOTSUPPORTED 23501
/* Deduplication is not supported for deduped disabled or non SIS volumes. */

#define EDELETEFAILED 21023
/* Error when deletion of a file fails */

#define EDIRDOESNOTEXIST 21020
/* Error when directory does not exist */

#define EDIRNOTWRITABLE 21021
/* Error when directory is not writable */

#define EDOMAINUSERAMBIGUOUS 23324
/* Domain user name is ambiguous. */

#define EDOMAINUSERNOTFOUND 23323
/* Domain user is not found in the database. */

#define EDPPOLICYINUSE 22282
/* The DP Policy is in use by one or more datasets. */

#define EDPPOLICYNODENOTFOUND 22222
/* Data protection policy node not found. */

#define EDPPOLICYNOTFOUND 22223
/* Data protection policy not found. */

#define EDRLICENSEREQUIRED 23414
/* The disaster recovery license is required */

#define EDSCONFLICTALREADYEXCLUDED 23809
/* The object to be added to the dataset's exclusion list is already in the exclusion list. */

#define EDSCONFLICTALREADYINDATASET 22293
/* Object, its ancestor or descendent is already in dataset.  */

#define EDSCONFLICTALREADYINRESPOOL 22294
/* Object, its ancestor or descendent is already in resource pool. */

#define EDSCONFLICTCANTFAILOVEROSSV 23403
/* An OSSV directory or host cannot be in the primary node of a DR dataset. */

#define EDSCONFLICTCANTMIRROROSSV 22295
/* OSSV is not allowed in mirror source node. */

#define EDSCONFLICTCANTSNAPSHOTOSSV 22296
/* Cannot apply snapshot schedule to OSSV. */

#define EDSCONFLICTDEDUPLICATION 23504
/* Conflicts while setting dedupe enabled secondary provisioning policy to a backup or mirror destination node.  */

#define EDSCONFLICTINCOMPATIBLEOBJTYPE 23807
/* The object user is trying add to a dataset is incompatible with the types of the existing member objects. */

#define EDSCONFLICTINCOMPATIBLEPOLICY 22334
/* The policy is not compatible with the dataset. */

#define EDSCONFLICTINVALIDVFILER 23342
/* vFiler is not valid. */

#define EDSCONFLICTMEMBERVFILERMISMATCH 23346
/* vFiler and members in the dataset node do not match. */

#define EDSCONFLICTNDRESTORE 23406
/* Operation is not permitted if non disruptive restore is enabled. */

#define EDSCONFLICTNOSMLICENSE 22297
/* There is no SnapMirror license installed. */

#define EDSCONFLICTNOSMSVLICENSE 22298
/* There is no SnapMirror or SnapVault license installed. Need to have at least one of them installed. */

#define EDSCONFLICTNOSVLICENSE 23404
/* There is no SnapVault license installed. */

#define EDSCONFLICTNOTEXCLUDED 23810
/* The object to be removed from the dataset's exclusion list is not in the exclusion list. */

#define EDSCONFLICTNOTLEAFNODE 22301
/* Operation cannot be performed on non-leaf node of dataset. */

#define EDSCONFLICTNOTROOTNODE 22300
/* Operation cannot be performed on non-root node of dataset. */

#define EDSCONFLICTOSSVNOTALLOWED 22335
/* OSSV is not allowed of this dataset. */

#define EDSCONFLICTOSVERSIONNOTCOMPATIBLE 23405
/* The OS version is not comaptible to support the operation. */

#define EDSCONFLICTPROVPOLICYNOTALLOWED 23340
/* Comment field is a system comment. */

#define EDSCONFLICTROOTNODE 22299
/* Operation cannot be performed on root node of dataset. */

#define EDSCONFLICTRPNOTALLOWED 23808
/* Resource pools are not allowed on a dataset that has an application policy assigned, or virtualization object members. */

#define EDSCONFLICTSRCDESTINSAMEAGGR 23514
/* Backup from the source data to destionation data in the same aggregate is not allowed. */

#define EDSCONFLICTTRANSPARENTMIGRATION 23500
/* Transparent migration checks for the dataset failed. */

#define EDSCONFLICTWITHANOTHERDATASET 23418
/* Object, its ancestor or descendent is already in another dataset. */

#define EDUPCAPABILITY 21044
/* Error when a specified capability is already assigned to a role */

#define EDUPLICATEROLE 21028
/* Error when a duplicate role name specified */

#define EDUPLICATEROLEREF 22292
/* The role already inherits from the specified role. */

#define EDUPLICATEUSER 23310
/* User with the given name already exists. */

#define EDUPLICATEUSERGROUP 23322
/* Usergroup with the given name already exists. */

#define EDUPOPERATION 21039
/* Error when a specified operation already exists */

#define EEDITINPROGRESS 22221
/* Another edit session is currently in progress. */

#define EEDITSESSIONCONFLICTINGOP 22264
/* The operation is incompatible with those already in the edit session. */

#define EEDITSESSIONINPROGRESS 22243
/* Edit session already in progress. */

#define EEDITSESSIONNOTFOUND 22240
/* Edit session not found. */

#define EEDITSESSIONOBJECTALREADYLOCKED 22263
/* Object already locked by another edit session. */

#define EEVENTCLASSEXISTS 21013
/* Event type being added already exists */

#define EEVENTGENERATEFAILED 21011
/* Failed to generate event */

#define EFILEDOESNOTEXIST 21022
/* Error when file does not exist */

#define EFILERNOTFOUND 23343
/* Filer not found. */

#define EGRAPHNOTFOUND 23339
/* Specified graph not found. */

#define EGROUPCOPYERROR 22272
/* Error during group copy operation. */

#define EGROUPDOESNOTEXIST 22228
/* No such resource group exists. */

#define EGROUPEXISTS 22274
/* A group with the same name already exists. */

#define EGROUPMOVEERROR 22273
/* Error during group move operation. */

#define EHOSTACCESSDENIED 22309
/* The Host rejected the operating system username or password. */

#define EHOSTADDDUPPRODID 22314
/* Tried to add a host with the same product id as an existing host. */

#define EHOSTADDMISMATCHPRODID 22325
/* The host being added is in the database, but with a different product id. */

#define EHOSTADDNOCONTACT 22312
/* Cannot contact the host. */

#define EHOSTADDNOFCSWITCH 22316
/* Licenseing prohibits adding an FC switch. */

#define EHOSTADDNOLICENSE 22322
/* The license is not available to add this type of host. */

#define EHOSTADDNONODES 22324
/* The licensed node limit has been exceeded. */

#define EHOSTADDNOTENABLED 22323
/* The backup host does not have snapvault enabled. */

#define EHOSTADDNOTRESOLVED 22313
/* Could not resolve the fqdn or ip address of the host. */

#define EHOSTADDTAKENOVER 22315
/* Host has been taken over by its cluster failover partner. */

#define EHOSTADDVFILERPARENTDELETED 22317
/* The parent host of the vfiler host has been deleted. */

#define EHOSTBADCONFIG 22328
/* Configuration error found on host. */

#define EHOSTCOMMUNICATION 22308
/* Unable to contact the Host Agent. */

#define EHOSTDOESNOTEXIST 21001
/* Host does not exist in the dfm database. */

#define EHOSTEXISTS 22311
/* Host already exists. */

#define EHOSTINUSE 22329
/* The host is being used for backup operations. */

#define EHOSTNDMPACCESSFAILED 22327
/* NDMP access failed. */

#define EHOSTNDMPTABLOOKUPFAILED 22331
/* Failed to retrieve the default ndmp credentials for a host add. */

#define EHOSTOSVERSIONNOTSUPPORTED 23304
/* Host's OS is not supported for the operation. */

#define EHOSTREQUESTDENIED 22310
/* The Host Agent was unable to change the password. */

#define EHOSTRSHACCESSFAILED 22336
/* RSH access denied on the host. */

#define EHOSTRUNMONFAILED 22319
/* Failed to run sysinfomon on the host just added. */

#define EHOSTVFILERADDFAILED 22330
/* Failed to add the vfilers for the host we just added. */

#define EHSNOTAUTHORIZED 23828
/* Host Service registration is not yet authorized. */

#define EHS_ALREADY_AUTHORIZED 23827
/* Host Service is already authorized. */

#define EHS_CONFIGURE_FAILED 23829
/* Host Service configuration failed. */

#define EHS_REGISTER_ERROR 23812
/* Host Service registration failed. */

#define EHS_UNREGISTER_ERROR 23811
/* Host Service un-registration from DataFabric Manager Server failed. */

#define EINCOMPATIBLEROLE 23331
/* Incompatible roles found on source and target hosts. */

#define EINCOMPATIBLEUSERGROUP 23332
/* Incompatible usergroups found on source and target hosts. */

#define EINVALIDALARMTIME 22231
/* Invalid time. */

#define EINVALIDAPPLICATIONNAME 21033
/* Error when an invalid application name is specified */

#define EINVALIDCAPABILITY 23306
/* Invalid capability specified. */

#define EINVALIDDESCRIPTION 21029
/* Error when an invalid description specified */

#define EINVALIDDOMAINUSERNAME 23325
/* Domain user name is invalid. */

#define EINVALIDEMAILADDR 22227
/* Invalid email address. */

#define EINVALIDEVENTCLASSEXP 22232
/* Invalid regular expression for event-class. */

#define EINVALIDEVENTSEVERITY 22260
/* Invalid severity level for the event. */

#define EINVALIDGROUPFILTER 23813
/* Group filter can not be applied to given query. */

#define EINVALIDGROUPNAME 22275
/* Specified group name is invalid. */

#define EINVALIDINPUT 21012
/* Invalid input */

#define EINVALIDJOBSTATE 23512
/* Invalid job state. */

#define EINVALIDJOBTYPE 23511
/* Invalid job type. */

#define EINVALIDLICENSE 22302
/* Invalid license key specified. */

#define EINVALIDLONGDESC 21036
/* Error when an invalid long description is specified */

#define EINVALIDMEMBER 22270
/* Specified member is not a groupable object type. */

#define EINVALIDMEMBERTYPE 22262
/* Invalid member type is specified. */

#define EINVALIDMIGRATIONSTATUS 23507
/* Invalid migration status for a particular migration operation. */

#define EINVALIDOBJECTTYPE 23336
/* The object type is invalid for the requested operation. */

#define EINVALIDOPERATIONNAME 21032
/* Error when an invalid capability name is specified */

#define EINVALIDOPERATIONTYPE 21034
/* Error when an invalid capability type is specified */

#define EINVALIDOPTION 23814
/* Invalid option. */

#define EINVALIDPASSWORDAGE 23313
/* Invalid password age specified for the user. */

#define EINVALIDPOLICYPROPERTY 22253
/* Invalid value specified for a property in the policy. */

#define EINVALIDQTREENAME 22225
/* invalid qtree name */

#define EINVALIDRESOURCE 21041
/* Error when a specified resource is invalid */

#define EINVALIDRESOURCETYPE 21038
/* Error when an invalid resource type is specified */

#define EINVALIDROLENAME 21027
/* Error when an invalid role name specified */

#define EINVALIDSHORTDESC 21037
/* Error when an invalid short description is specified */

#define EINVALIDSTORAGESETMAP 22248
/* Storage set is not empty. */

#define EINVALIDTAG 21002
/* Invalid tag specified to get the iterator. */

#define EINVALIDTRAPADDR 22230
/* Trap Address invalid. */

#define EINVALIDUSERFULLNAME 23311
/* Invalid full-name specified for the user. */

#define EINVALIDUSERGROUPNAME 23321
/* Usergroup name is invalid. */

#define EINVALIDUSERNAME 21046
/* Error when a role is not found in the database */

#define EJOBALREADYABORTED 22219
/* Specified job already aborted. */

#define EJOBALREADYCOMPLETED 22218
/* Specified job already completed execution. */

#define EJOBCANNOTBEABORTED 22220
/* Specified job can not be aborted. */

#define EJOBCANNOTBESTORED 23415
/* Specified job can not be stored in the database. */

#define EJOBDOESNOTEXIST 22217
/* Specified job does not exist. */

#define ELICENSEINUSE 22285
/* This license is being used by a different host. */

#define EMAXBACKUPMOUNT 23824
/* Maximum Number of Mounted Backups. */

#define EMEMBERALREADYINGROUP 22269
/* Specified member is already present in the group. */

#define EMEMBERNAMEAMBIGUOUS 22271
/* Specified member name is ambiguous. */

#define EMEMBERNOTINGROUP 22268
/* Specified member is not present in the group. */

#define EMIGRATEDESTINATIONSELECTIONFAILED 23508
/* A valid destination during resource selection was not found. */

#define EMIGRATENOTSUPPORTED 23509
/* Migration not supported */

#define EMULTISTORENOTLICENSED 23344
/* Multistore not licensed. */

#define ENAMENOTFOUND 21003
/* Invalid option name given which does not exist in the db. */

#define ENDRESTORENOTPOSSIBLE 23407
/* A non disruptive restore is not possible. One the reasons may be a partial qtree restore. */

#define ENOBACKUPINPROGRESS 21025
/* Error when there is no backup process to abort */

#define ENODENOTDRCAPABLE 23413
/* The node is not Disaster Recovery capable */

#define ENOFAVORITES 23315
/* No favorite reports for the user. */

#define ENOPERFTHRESHOLDVIEWEXISTS 23330
/* No perf view exists for the threshold being set. */

#define ENORECENTVIEWED 23316
/* No recently viewed reports for the user. */

#define ENOSUCHEVENT 22257
/* No such event found. */

#define ENOSUCHEVENTCLASS 21014
/* Event type does not exist */

#define ENOTASSIGNEDCAPABILITY 21043
/* Error when a specified capability is not assigned to a role */

#define ENOTASSIGNEDROLE 21042
/* Error when a specified resource is invalid */

#define ENOTCUSTOMEVENTCLASS 21010
/* Passed event class is not a custom event class */

#define ENOTFOUNDOPERATION 21040
/* Error when a capability does not exist in the database */

#define ENOTFOUNDROLE 21030
/* Error when a role is not found in the database */

#define ENOTFOUNDUSER 21047
/* Error when a role is not found in the database */

#define ENOTINDATASET 22242
/* Member not in dataset. */

#define ENOTINGROUP 22245
/* Member not in group. */

#define ENOTINHERITEDROLE 21045
/* Error when a specified role is not inherited by a role */

#define EOBJECTAMBIGUOUS 22211
/* Multiple objects are present with the same name in database. */

#define EOBJECTEXISTS 22284
/* The specified object cannot be added because it already exists. */

#define EOBJECTEXISTSINRESOURCEPOOL 22208
/* Object being added to Resource pool already exists in that resource pool. */

#define EOBJECTINANOTHERDYNAMICREFERENCE 22206
/* Object being added to Resource pool is in another Resource pool/Storage set. */

#define EOBJECTINDIRECTMEMOFANOTHERDYNAMICREF 23419
/* Object being added to Resource pool is in another Resource pool and it's an indirect member of the Resource pool. */

#define EOBJECTNOTFOUND 22255
/* Object not found in DFM Database. */

#define EOBJECTNOTFOUNDINBACKUP 23823
/* An application object requested to be restored, is not present in the specified backup. */

#define EOBJECTNOTINRESOURCEPOOL 22207
/* Object being deleted from Resource pool does not exist in that resource pool. */

#define EOBJECTNOTRESTORABLE 23822
/* An application object requested to be restored, is not restorable. */

#define EONLINENOTPOSSIBLE 23521
/* Operation is not supported due to host OS version incompatability. */

#define EOPERATIONISPERMANENT 22289
/* An attempt was made to modify or delete a permanent operation */

#define EOPERATIONNOTSUPPORTED 23513
/* Operation is not supported due to host OS version incompatability. */

#define EOPERATIONTIMEDOUT 22333
/* Operation failed due to timeout exceeded. */

#define EOSSVCANTTAKESNAPSHOTS 22288
/* A snapshot schedule is being set for a policy's root node, but the policy has been applied to a dataset whose root node contains OSSV directories. */

#define EPARENTGROUPDOESNOTEXIST 22276
/* Specified parent group does not exist. */

#define EPARENTGROUPNAMEAMBIGUOUS 22267
/* Specified parent group name is ambiguous. */

#define EPASSWORDAGENOTSUPPORTED 23312
/* Password age is not supported in the current ONTAP release. */

#define EPATHDOESNOTEXIST 22291
/* The specified path was not found. */

#define EPERFEXPORTINPROGRESS 23701
/* There is already a data export job in progress.  */

#define EPERFTEMPLATEEXISTS 23417
/* The performance template already exists */

#define EPERFUPDATEDISABLED 23314
/* Performance Advisor object updates sre disabled. */

#define EPOLICYEXISTS 22261
/* Policy already exists. */

#define EPOLICYNOTMODIFIABLE 22251
/* Policy cannot be modified or deleted because its is-modifiable attribute is false. */

#define EPOLICYTOPOLOGYCHANGED 22252
/* The requested modification changes the topology of the policy graph. */

#define EPROCESSKILLFAILED 21026
/* Error when kill failed for a process */

#define EPROVISIONFAILED 23518
/* Provisioning a dataset member failed. */

#define EPROVPOLICYINUSE 23338
/* Provisioning policy is in use by datasets. */

#define EQTREEALREADYEXISTS 22226
/* qtree already exists */

#define EQTREEDELETEDPARENT 22236
/* Indicates that a qtree parent (host/filer or volume) is currently deleted.  A qtree may not be added (or monitored) by DFM under this situation. */

#define EQTREEDOESNOTEXIST 22224
/* qtree does not exist */

#define EQTREEMANAGEDBYAPP 22234
/* qtree is being managed by an application */

#define EQTREEMONITOROFFFAIL 22238
/* Could not stop monitoring qtree */

#define EQTREEMONITORONFAIL 22237
/* Could not start monitoring qtree */

#define EQTREEUNDELETEFAIL 22235
/* Failed to undelete qtree */

#define EREPORTAMBIGUOUS 23318
/* Report of the same name exists in different applications. */

#define EREPORTCATEGORYNOTFOUND 23816
/* The input report category does not exist in DFM. */

#define EREPORTNOTFOUND 23326
/* Specified report could not be found. */

#define EREPORTNOTLICENSED 23334
/* The report scheduled is not licensed. */

#define EREPORTNOTSCHEDULABLE 23335
/* The report cannot be scheduled. */

#define EREPORTOUTPUTDELETEERROR 23327
/* Error in deleting the report output. */

#define EREPORTOUTPUTFILENOTFOUND 23333
/* The report schedule did not generated any report output. */

#define EREPORTOUTPUTFILEREADERROR 23328
/* Error in reading the report output. */

#define EREPORTOUTPUTNOTFOUND 23320
/* Invalid report output id specified. */

#define EREPORTSCHEDULEDELETEERROR 23329
/* Error in deleting report schedule. */

#define EREPORTSCHEDULEDUPLICATE 23319
/* Report Schedule already exists. */

#define ERESOURCEPOOLDOESNOTEXIST 22204
/* Resource pool does not exist. */

#define ERESOURCEPOOLEXISTS 22205
/* Resource pool already exists. */

#define ERESOURCEPOOLINUSE 22210
/* Resource pool is in use by a Storage set. */

#define ERESOURCEPOOLNOTEMPTY 22209
/* Resource pool is not empty. */

#define EROLEAMBIGUOUS 23305
/* Role name is ambiguous. */

#define EROLEASSIGNED 21031
/* Error returned when the administrator has already been assigned the role. */

#define EROLEISPERMANENT 21048
/* An attempt was made to modify a permanent and fixed role. */

#define EROOTSTORAGESET 22249
/* Storage set is attached to root node of policy graph. */

#define ERUNASUNSUPPORTED 22229
/* Run as option not supported in Windows Management Station */

#define ESCHEDULEDUPLICATE 22202
/* Schedule already exists */

#define ESCHEDULEINUSE 22203
/* Schedule is being used by another schedule */

#define ESCHEDULEINVALIDINPUT 22200
/* Invalid Input Parameter(s) found in the schedule. */

#define ESCHEDULENOTFOUND 22201
/* Schedule not found */

#define ESCHEDULENOTMODIFIABLE 22286
/* Schedule cannot be modified or deleted because it is a permanent or sample schedule. */

#define ESCRIPTJOBRUNNING 21016
/* Script/Schedule/Job could not be deleted since jobs were running */

#define ESCRIPTPERMERROR 21019
/* Permission error when performing script operations */

#define ESERVICEEXISTS 23515
/* The Storage Service already exists. */

#define ESERVICEISATTACHED 23517
/* The Dataset is attached to Storage Service. */

#define ESERVICESTATEUNKNOWN 22320
/* Could not find out if the service was actually started/stopped.. */

#define ESNAPSHOTNOTFOUND 23337
/* Snapshot not found. */

#define ESPACEMGMTCONFLICTOP 23803
/* Space management conflicting operation. */

#define ESPACEMGMTSESSIONINPROGRESS 23801
/* Space management session already in progress. */

#define ESPACEMGMTSESSIONNOTFOUND 23802
/* Space management session not found. */

#define ESPCMGMTNOSUCHOP 23804
/* No such space management operation in the session. */

#define ESTORAGESERVICEINUSE 23516
/* The Storage Service contains datasets. */

#define ESTORAGESETNOTEMPTY 22247
/* Storage set is not empty. */

#define ESTORAGESETNOTINDATASET 22283
/* Storage set is not a part of the dataset. */

#define ESTORAGE_MAP_NOT_FOUND 23831
/* The storage map for an application object has not been discovered. */

#define ESYSTEMCOMMENTFIELD 23303
/* Comment field is a system comment. */

#define ETHRESHOLDEXIST 23317
/* Threshold already exists. */

#define ETHROTTLEDUPLICATE 22214
/* Throttle schedule already exists */

#define ETHROTTLEINUSE 22215
/* Throttle schedule currently in use */

#define ETHROTTLEINVALIDINPUT 22216
/* Invalid Input Parameter(s) found in the throttle schedule. */

#define ETHROTTLENOTFOUND 22213
/* Throttle schedule not found */

#define ETHROTTLENOTMODIFIABLE 22287
/* Throttle schedule cannot be modified or deleted because it is a permanent or sample throttle schedule. */

#define EUNDEDUPENOTSUPPORTED 23502
/* Undeduplication is not supported for deduped enabled or non SIS volumes. */

#define EUNKNOWNFAILOVERCONFIG 21005
/* Unknown failover configuration name */

#define EUNUSEDAPPLICATIONOBJECTSETTING 23820
/* A setting used only for application objects was supplied when no application objects are involved. */

#define EUSERAMBIGUOUS 23309
/* User name is ambiguous. */

#define EUSERGROUPAMBIGUOUS 23308
/* Usergroup name is ambiguous. */

#define EUSERGROUPNOTFOUND 23307
/* Specifies usergroup is not found in the DB. */

#define EVFILERINTERFACENOTSET 23520
/* Default vFiler interface of the Filer is not set. */

#define EVFILERTEMPLATEEXISTS 23341
/* vFiler template already exists. */

#define EVFILERTEMPLATEINUSE 23519
/* VFiler template is in use. */

#define EVIEWEXISTS 21004
/* View exists. */

#define EXMLVALIDATEFAIL 21015
/* Package xml fails to validate to schema */

#define EZIPFILEERROR 21017
/* Script ZIP File opening failed. */

#define EZIPFILEEXTRACTERROR 21018
/* Error when extracting a particular file from the zip file */

